### ISSUE TITLE
关于这个模块的一些疑惑？

### ISSUE THREAD

**Issue by makangzhe** [murufeng/EPSANet#10]
1. 为什么没有做ResNet18的实验？我想做的轻量化网络，在ResNet18中加入这个模块会有提升嘛？
2. 如果自己加入这个模块，模型需要从头开始训练嘛，还是可以用已有的预训练模型？

希望能够得到您的回复，万分感谢！

**Comment by murufeng** [comment]
我们没有做ResNet18，可能你需要自己重新训练了，这个模块放到ResNet中是会有提升的，可以先尝试一下！

> 1. 为什么没有做ResNet18的实验？我想做的轻量化网络，在ResNet18中加入这个模块会有提升嘛？
> 2. 如果自己加入这个模块，模型需要从头开始训练嘛，还是可以用已有的预训练模型？
> 
> 希望能够得到您的回复，万分感谢！
