### ISSUE TITLE
您好，关于small和large的问题

### ISSUE THREAD

**Issue by beauty-snowman** [murufeng/EPSANet#15]
small的分组数是[1,4,8,16]，large是[32,32,32,32]，分组数变多网络参数不是应该变小么，但是为什么您论文写的是large g=32网络参数和计算量比small大

**Comment by eslambakr** [comment]
Do you find out an answer for this?
If yes, can u please share it with us.

Thanks in advance.

**Comment by BeEyesana** [comment]
> Do you find out an answer for this? If yes, can u please share it with us.
> 
> Thanks in advance.



You can check table 1 in the paper. In large model the PSA module splits the input feature map into more groups, but meanwhile the first conv layer and PSA module in every block have more input and output channels.
More groups reduce the number of params, while more channels increase it. I think these 2 factors contribute to the final number of params together and make it a bit larger than the small one.

**Comment by Channing26** [comment]
可以看论文中的table1，large的PSA module的input channel也增加了

> small的分组数是[1,4,8,16]，large是[32,32,32,32]，分组数变多网络参数不是应该变小么，但是为什么您论文写的是large g=32网络参数和计算量比small大
