### ISSUE TITLE
为啥没看见你PSA模块的实现，只看见SEWeight模块

### ISSUE THREAD

**Issue by muyihao** [murufeng/EPSANet#3]

**Comment by lmk123568** [comment]
hhh，可能是还没完全release

**Comment by lmk123568** [comment]
> hhh，可能是还没完全release

现在就是不知道torch1.9能不能运行这个代码

**Comment by murufeng** [comment]
release还需要一段时间，Pytorch>=1.0.0都可以运行

> > hhh，可能是还没完全release
> 
> 现在就是不知道torch1.9能不能运行这个代码

**Comment by muyihao** [comment]
好吧，那是我来早了

**Comment by lmk123568** [comment]
> release还需要一段时间，Pytorch>=1.0.0都可以运行
> 
> > > hhh，可能是还没完全release
> > 
> > 
> > 现在就是不知道torch1.9能不能运行这个代码

大家喊你催更啦

**Comment by murufeng** [comment]
> > release还需要一段时间，Pytorch>=1.0.0都可以运行
> > > > hhh，可能是还没完全release
> > > 
> > > 
> > > 现在就是不知道torch1.9能不能运行这个代码
> 
> 大家喊你催更啦

已经更新了，欢迎大家fork+ star
