### ISSUE TITLE
创新点

### ISSUE THREAD

**Issue by hjhjb** [murufeng/EPSANet#7]
论文中提出的PSA模块的创新点在哪里啊，从作者给出的中间特征图也没有体现出多尺度的意思

**Comment by lmk123568** [comment]
> 论文中提出的PSA模块的创新点在哪里啊，从作者给出的中间特征图也没有体现出多尺度的意思

就是添加几个不同卷积核提取不同大小，就当多尺度了呗

**Comment by murufeng** [comment]
对的，我们主要利用不同尺度的卷积核来进行特征图空间信息提取，这就是多尺度的体现！另外，我们对通道是进行切分的，最后融合的多尺度特征图总的通道数是保持不变的。通过上述操作，可以使得模型对多尺度特征图空间信息提取的细粒度更高！

> > 论文中提出的PSA模块的创新点在哪里啊，从作者给出的中间特征图也没有体现出多尺度的意思
> 
> 就是添加几个不同卷积核提取不同大小，就当多尺度了呗

**Comment by lmk123568** [comment]
> 对的，我们主要利用不同尺度的卷积核来进行特征图空间信息提取，这就是多尺度的体现！另外，我们对通道是进行切分的，最后融合的多尺度特征图总的通道数是保持不变的。通过上述操作，可以使得模型对多尺度特征图空间信息提取的细粒度更高！
> 
> > > 论文中提出的PSA模块的创新点在哪里啊，从作者给出的中间特征图也没有体现出多尺度的意思
> > 
> > 
> > 就是添加几个不同卷积核提取不同大小，就当多尺度了呗

所以，来个pretrain model weight？
