### ISSUE TITLE
Some doubts about paper and code 论文和代码的一些疑惑

### ISSUE THREAD

**Issue by frankxzq** [murufeng/EPSANet#9]
I read the EPSAnet paper and code, but found some differences. In the paper, it is proposed to divide the channels of the feature map into S groups, and then convolve the S groups separately. The number of convolutional channels remains unchanged. The groups are all C/S, but I think that in the code, all input channels are convolved, and the number of output channels of the convolution becomes C/S. May I ask, which one of the two should be followed?
拜读了EPSAnet的论文和代码，但是发现有些不一样的地方，在论文中提出将feature map的通道分成S组，然后对这S组再分别进行卷积，卷积出来的通道数不变，每组都是C/S,但是我看在代码上是对所有的输入通道都进行卷积，卷积的输出通道数变成了C/S，请问，这两个应该遵从哪一个呢？

**Comment by murufeng** [comment]
follow the code.

**Comment by murufeng** [comment]
> I read the EPSAnet paper and code, but found some differences. In the paper, it is proposed to divide the channels of the feature map into S groups, and then convolve the S groups separately. The number of convolutional channels remains unchanged. The groups are all C/S, but I think that in the code, all input channels are convolved, and the number of output channels of the convolution becomes C/S. May I ask, which one of the two should be followed?
> 拜读了EPSAnet的论文和代码，但是发现有些不一样的地方，在论文中提出将feature map的通道分成S组，然后对这S组再分别进行卷积，卷积出来的通道数不变，每组都是C/S,但是我看在代码上是对所有的输入通道都进行卷积，卷积的输出通道数变成了C/S，请问，这两个应该遵从哪一个呢？

follow the code.
